name: "build figures"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
        

      - name: install packages
        run: pip install -r requirements.txt

      - name: build figures
        run: |
          python build.py

      - name: push figures
        run: |
          git config --global user.email djohan20@aau.student.dk
          git config --global user.name djohan20@aau.student.dk

          export INIT_DIR=$(pwd)
          export TEMP_DIR=$(mktemp -d)

          cd "$TEMP_DIR"
          git clone --single-branch --depth 1 --branch master https://djohan20%40aau.student.dk:djohan20%40student.aau.dk@git.overleaf.com/6502c96681431d837d9e5b7b overleaf_project 
          cd overleaf_project
          
          rm -rf "$TEMP_DIR/overleaf_project/built_figures"
          cp -ra "$INIT_DIR/build" "$TEMP_DIR/overleaf_project/built_figures" 

          git add built_figures/
          git commit -m "Add built figures"

          git push https://djohan20%40aau.student.dk:djohan20%40student.aau.dk@git.overleaf.com/6502c96681431d837d9e5b7b -u master

